"""add column update_at
exit


Revision ID: 6e1a9e51d58a
Revises: 75382eb471dc
Create Date: 2024-11-29 23:35:26.091467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e1a9e51d58a'
down_revision: Union[str, None] = '75382eb471dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parts', schema='test')
    op.create_table('parts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article', sa.String(), nullable=True),
    sa.Column('article_unit', sa.String(), nullable=True),
    sa.Column('serial_number_machine', sa.String(), nullable=True),
    sa.Column('alternative_article', sa.String(), nullable=True),
    sa.Column('name_eng', sa.String(), nullable=True),
    sa.Column('name_ru', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('part_type', sa.String(), nullable=True),
    sa.Column('description_custom', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('trade_mark', sa.String(), nullable=True),
    sa.Column('qty_in_unit', sa.Integer(), nullable=True),
    sa.Column('country_eng', sa.String(), nullable=True),
    sa.Column('s_code', sa.String(), nullable=True),
    sa.Column('path_catalog', sa.String(), nullable=True),
    sa.Column('path_documentation', sa.String(), nullable=True),
    sa.Column('path_photo', sa.String(), nullable=True),
    sa.Column('path_avatar', sa.String(), nullable=True),
    sa.Column('hashtags', sa.String(), nullable=True),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__parts')),
    # sa.UniqueConstraint('article', name=op.f('uq__parts__article')),
    schema='test'
    )
    op.drop_table('user_account', schema='test')
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('fullname', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__user_account')),
    schema='test'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_account', schema='test')
    op.drop_table('parts', schema='test')
    # ### end Alembic commands ###
